apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "patient-api"
        dapr.io/app-port: "8000"
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: backend
          image: patientdemoacr.azurecr.io/backend:v1
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-env